name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: checkout submodules
      run: git submodule update --init --recursive
    - name: build image
      run: docker build -t natalie .
    - name: test with gcc
      run: make docker_test
    - name: test with clang
      run: make docker_test_clang
    - name: test with valgrind
      run: make docker_test_valgrind
    - name: coverage report
      run: make docker_coverage_report
    - uses: actions/upload-artifact@v1
      with:
        name: coverage-report
        path: coverage-report
